import { Poppins } from "next/font/google"; 
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import Footer from "@/components/Footer";

// Initialize Poppins font
const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppinsFont.variable}>
        <Header/>
        <PageTransition>
          {children}
        </PageTransition>
        <Footer/>
      </body>
    </html>
  );
}
